### ISSUE TITLE
sh3 proxy ini

### ISSUE THREAD

**Issue by matt8928** [07151129/sh3proxy#16]
Hi, thx for the "mod" its awesome :)

This is a small problem, can i rearrange the text in the ini file, its a pain in the ass to read the text 

btw have you found a permanent fix for the frame jitter? i have tried the alt fix, seems to work perfectly most of the time, had a slowdown in a corridor in the otherworld church, fps went down to 30. Is that bad? don't really know what you mean by break the engines clock?

**Comment by 07151129** [comment]
> This is a small problem, can i rearrange the text in the ini file, its a pain in the ass to read the text

Are you using Microsoft Notepad to edit the ini? It does not recognise [LS newlines](https://en.wikipedia.org/wiki/Newline). Perhaps I should mention this in Readme. I might also start using CRLF in the .ini.

I have not been looking into frame jitter issues anymore. AltFix was intended as a temporary fix, since it makes in-game events desynchronise and happen at wrong speed. Deriving a better fix requires a good understanding of the synchronisation code. I will see if I can get a week or two in February to fix this and other issues.
