### ISSUE TITLE
black bars on both sides of screen after v0.8.3

### ISSUE THREAD

**Issue by matt8928** [07151129/sh3proxy#21]
Hi, thanks for your continued work on sh3proxy

after the update v0.8.3 i get thin black bars on left and right side of screen, thicker on the left side.
can you make an option to disable the vertical FOV being adjusted according to horozontal FOV?
or will you adjust it further

keep up the good work ;)

**Comment by 07151129** [comment]
![screen shot 2017-08-05 at 19 25 33](https://user-images.githubusercontent.com/3441064/28997029-5a1eb8d4-7a14-11e7-9ecf-98ee636ec9eb.png)

Are the bars the same as on the above screenshot? I have them even if I don't apply any video patches, so it doesn't seem to be caused by sh3proxy. Both bars appear to be 5 pixels wide.

**Comment by matt8928** [comment]
yeah, i guess i just didnt remember the bars, and they have about the same width on each side. sorry for wasting your time

**Comment by AeroWidescreen** [comment]
@07151129 Hello again. Oddly enough, these black bars can be adjusted in size or completely disabled. The purpose they have is unknown to me, but we've had their size at 0 for a long time (day 1?) and haven't had issues with that.

https://github.com/ThirteenAG/WidescreenFixesPack/blob/master/source/SilentHill3.WidescreenFix/dllmain.cpp#L283

41BE64 & 41BB2D
