### ISSUE TITLE
Customizable Vertical FOV and Color Adjustments

### ISSUE THREAD

**Issue by sh3f4n96** [07151129/sh3proxy#22]
Greetings! 
First of all I'd like to thank you for creating such an awesome tool, SH3 is my favourite video game and playing it on pc with high resolutions and great performance is really nice. Thank you so much!

I've started using this cool wrapper some months ago, despite from the other tools I managed to get everything I needed thanks to the various customizable options inside the .ini file. I think this is what makes this tool the best out there.
Now, there are only two more settings that I would really appreciate. These are just ideas, but as I think they could be useful also for other players so I'm gonna post them here:

1) Customizable Vertical FOV : I read from an old post that vertical fov gets automatically set now, it works good enough but unfortunately I noticed that it is not 100% perfect... horizontal fov works really fine but I think that the vertical one is missing some degrees and in my case I can't get the perfect 16:9 fov combination on a full-hd resolution. 
Besides, I think that customizable vertical fov could be useful to set the perfect fov in each situation, another issue that I think it could be fixed by adding a customizable vertical fov is that at the moment it is possible to see "unwanted stuff" in the cutsscenes (an example, the beginning of the cutscene in which Heather walks away from happy burger you can actually see her suddenly getting stopped after passing the street lamp (when her animation ends she gets stuck), which is something that you are not supposed to see.
2) Colors Management : in my opinion, in SH3 it is really important to get the perfect colors and in my case I'm experiencing some problems just because I have an optimus laptop and I can't properly set saturation and contrast from my nvidia card panel (as you know, in optimus laptops you can only configure 3d settings in nvidia panel).
I would be really happy if it could be possible to configure colors saturation and contrast inside the .ini file, other d3d8 wrappers like dgvoodoo does have this kind of settings and I think that it would be awesome to have this configurations inside the .ini file, in this way everyone could get the perfect colors in each different situation (for me, SH3 looks even better when the colors are a bit too saturated).

What do you think about implementing this two new features? 
Please let me know your opinion and ideas.

Again, thank you so much for your work and attention.

**Comment by 07151129** [comment]
Hi,

> horizontal fov works really fine but I think that the vertical one is missing some degrees and in my case I can't get the perfect 16:9 fov combination on a full-hd resolution.

Yes, the vertical FOV might be off by a few degrees. The main reason is that the coefficients I am patching in game do not directly go to the [projection matrix](https://msdn.microsoft.com/en-us/library/windows/desktop/bb147302(v=vs.85).aspx), but rather are used as an input to a function that performs some arithmetics with them first. Unfortunately, I was not able to understand the logic behind these calculations, and while I managed to derive a formula for horizontal FOV based on the observed values, I'm still not certain about vertical FOV. The obvious solution would be to patch the projection matrix directly, but then the transformation is happening too late, and light sources are located at a wrong angle to the camera. So while it is possible to pass an arbitrary vertical FOV to the game, unless a proper formula is used, the resulting angle will still be wrong.

> Colors Management

So what happens when you try to adjust colour coefficients in game?

**Comment by sh3f4n96** [comment]
Hi,

thanks for your feedback.

I understand the issue you're facing with vertical FOV. Maybe you already checked it, but if this can help you I noticed that the Widescreen Fix by Aero always finds the correct horizontal and vertical fov formula. That wrapper doesn't let you configure custom fov settings like in your tool, but in my opinion it always seems to set the correct fov on each resolution. Check it out if you like ;)

Regarding colors, maybe I didn't explain myself well... 
As you know you can only set brightness and rgb gamma inside the options menu, I have no problems with them and I managed to get the proper brightness in game.
My issue is that there's no option for colors saturation/chroma and in my case the colors look a bit "unsaturated" for this game. My other games look correct in terms of colors, also the other software, but for SH3 I'd like to make the colors "warmer" because of its genre.
If I could I would simply increase the saturation from nvidia card panel, but I can't because in most laptops you can only manage the saturation for the Intel graphics card (as you may understand I can't use the Intel card for this game because of performance issues).
It's just an idea, but I wanted to ask you if you think that it would be useful to add a setting in your wrapper to make the colors "cooler" or "warmer", something like a customizable parameter that works on a range that goes from 0 (unsaturated, black and white), to 50 (default saturation) and up to 100 (oversaturated).
It should be possible to develop this function, because for example you can manage this in dgvoodoo2 wrapper in the exact way I explained above. That wrapper works on d3d8 and the color function becomes really useful for a lot of people when trying to correct the colorfulness for old games.

Let me know if everything is clear now.
Thanks in advance.

**Comment by 07151129** [comment]
> Maybe you already checked it, but if this can help you I noticed that the Widescreen Fix by Aero always finds the correct horizontal and vertical fov formula. 

Widescreen Fix uses a [different](https://github.com/07151129/sh3proxy/issues/20#issuecomment-319492297) method of tweaking FOV. Furthermore, it just passes correct width to height rate to the engine, and lets it figure out both angles on their own. This works fine, but does not let user tweak the angle at all.

> My issue is that there's no option for colors saturation/chroma

This is a bit out of sh3proxy scope, and it would require me to hook the drawing routines of the game to access the pixel buffer. Since there are existing solutions for applying these effects, I suggest you instead patch sh3.exe PE header (e.g. using LordPE) to load sh3proxy dll (you can rename d3d8.dll to e.g. sh3proxy.dll). Then you can use any d3d8 wrapper you like, as sh3proxy itself does not actually touch Direct3D calls, so it should be compatible with these wrappers.

**Comment by sh3f4n96** [comment]
> Widescreen Fix uses a different method of tweaking FOV. Furthermore, it just passes correct width to height rate to the engine, and lets it figure out both angles on their own. This works fine, but does not let user tweak the angle at all.

Everything clear, thank you. 
I got curious and decided to make some tests in the last hours, fortunately I managed to make a really simple app that will help me get the correct 16:9 aspect that I needed. Just made some tests and everything seems perfect, all right then :)

> I suggest you instead patch sh3.exe PE header (e.g. using LordPE) to load sh3proxy dll (you can rename d3d8.dll to e.g. sh3proxy.dll). Then you can use any d3d8 wrapper you like.

Thanks for the advice. 
Yes I already tried to make sh3.exe load a renamed d3d8.dll and then tried adding dgvoodoo to manage the saturation, but unfortunately it seems that dgvoodoo wrapper always adds some default configuration which mess up sh3 graphics and fps.... also made some tests with SweetFX and others but I got no luck... 
I'll see if I can find some other ways to do this, nothing really important it was just to improve the gaming experience.

**Comment by 07151129** [comment]
> Yes I already tried to make sh3.exe load a renamed d3d8.dll and then tried adding dgvoodoo to manage the saturation, but unfortunately it seems that dgvoodoo wrapper always adds some default configuration which mess up sh3 graphics and fps.... also made some tests with SweetFX and others but I got no luck...

Does the problem occur even if sh3proxy is disabled? If it does, then the issue is really out of sh3proxy scope.

**Comment by sh3f4n96** [comment]
> Does the problem occur even if sh3proxy is disabled? If it does, then the issue is really out of sh3proxy scope.

Yes you're right, sh3proxy works absolutely great. The problem is dgvoodoo that just seems not to work fine with sh3. 
Just closed this issue a few hours ago, thanks for clarifying my doubts.
