### ISSUE TITLE
Noise Filter and Contrast

### ISSUE THREAD

**Issue by CHNSK** [07151129/sh3proxy#5]
Hey guys, maybe you know that turning off the noise filter tends to lowers the game's contrast for some reason. This is not an issue caused by sh3proxy, it's just one of the shortcomings of this port. What do you think about this. Can this be fixed?

**Comment by CHNSK** [comment]
Since no one's interested and being less relevant to the wrapper, feel free to close it if you like. And sorry if this was over reaching.

And btw what your next plan about Silent Hill 3, are you on a certain thing? Just curious.

**Comment by 07151129** [comment]
I didn't look too much into the issue (reverse engineering the game takes time), so I suggest we keep it open. Next release (mid-autumn?) will hopefully include the fix.

sh3proxy is pretty much complete now with all its major features implemented. The only one missing is a proper framerate drop fix, but the issue seems to require a better understanding of the engine, which is hard to achieve without having its source code. (Konami would have fixed that bug if they could, wouldn't they?)

**Comment by CHNSK** [comment]
Any chance on implementing AA, like the SH2 modern compatibility fix and high DOF resolution? Turning it off is a nice option to have but It seems  dof is not only used for cutscenes. There are some in-game effects getting lost when it turned off, like the strange curtain room won't have the steam under it and alternate hospital wall's blur effect and the church's drop effects on the ground.

**Comment by 07151129** [comment]
> Any chance on implementing AA

Simple MSAA support can be added, although I can imagine people already using other software to achieve this (e.g. Nvidia panel).

> It seems dof is not only used for cutscenes

That's worrisome. Can you provide some screenshots?

**Comment by CHNSK** [comment]
I've never been able to add AA through Nvidia control panel,  probably my old laptop card doesn't support it, I have only Q/CSAA and standart 2/8/16x AA on the panel.

> That's worrisome. Can you provide some screenshots?

Hospital Walls
DOF on:  http://imgur.com/a/qcIBT
DOF off:  http://imgur.com/a/2fB1p

Hospital Curtain Room
DOF on:  http://imgur.com/VUFHwSJ
DOF off(no steam):  http://imgur.com/a/OIJWd

Church Fan:
On:  http://imgur.com/a/5bvHo
Off:  http://imgur.com/a/DaEvI
In this particular room lighting gets weirder in absence of dof
Off:  http://imgur.com/a/4XfKt

Church Elevator
On:  http://imgur.com/a/uNzZ4
Off:  http://imgur.com/a/wa6tC

The effect is also present in the Church hallway walls where Valtiel fiddling with a Nurse but it's not noticeable on screenshot, however in game it's very clear.  

These may not look good on screenshots, but in game they are moving in a complex way to provide a neat trippy effect, they're not static.

**Comment by 07151129** [comment]
Thanks for the screenshots, I was able to fix this.

After some research, I concluded I won't be implementing anti-aliasing. d3d multisampling can't be used due to the way the engine uses texture as a rendertarget (but not vice versa, and multisampling can only be enabled for the former). d3d8 only supports pixel shader versions up to 1.4, which is too limited for implementation of techniques like FXAA. Probably a good idea is to use a d3d8 to d3d9 converter along with fxaa-injector, or something like Reshade.

**Comment by 07151129** [comment]
> turning off the noise filter tends to lowers the game's contrast for some reason

Does it happen only during the gameplay, or also in menu? I fail to reproduce the bug.

**Comment by CHNSK** [comment]
I think it happens only during gameplay. Took some screenshots, while in the game it's quite clear, I can't tell the difference between menus, they look very same to me. 

In Game
On: http://imgur.com/QTVMwu4
Off: http://imgur.com/eGnTwL4

Main Title
On: http://imgur.com/RD4u8OR
Off: http://imgur.com/QCgm1Lo

Inventory Screen
On: http://imgur.com/M43leUN
Off: http://imgur.com/D2v9KXJ

**Comment by 07151129** [comment]
I see what you meant now. I don't think this is a bug, though: noise filter is supposed to randomly modify luminance of image, so it's natural that some areas are lighter or darker than without the filter.

**Comment by CHNSK** [comment]
Oh, I always thought it was a kind of bug and that's why the developers never wanted us to turn it off.  It's better to try and apply things like reshade/sweetfx like you suggest, I think SH3 may benefit the advantages they could offer in that regard.  And I'm truly sorry for wasting your time, I should have explained myself more clearly.
