### ISSUE TITLE
Internal resolution, add render distance, fog density

### ISSUE THREAD

**Issue by Keith94** [07151129/sh3proxy#8]
There's another fix available for this game (http://ps2wide.net/pc.html#sh3) which includes some configurable options for _internal resolution_ + _render distance_  + _fog density_:

```
[MAIN]
int_width = 1280
int_height = 720

[MISC]
add_render_distance = 0.0 // original value 0.0;

[FOG]
fog_density = 672.0 // original value 448.000000;
```

I was wondering if these are features worth adding to sh3proxy if possible.

**Comment by 07151129** [comment]
They can be added, although I am not sure whether they make sense:
1. All sane internal resolutions are provided by the game (having non power of two resolutions is an interesting idea, didn't test if d3d8 supports them properly though)
2. Render distance seems to be optimal, not sure why change it except for debugging
3. Fog density is adjusted automatically based on aspect rate (`CorrectFog` option)

I would like to see what other users think about adding these features.

**Comment by CHNSK** [comment]
I've been messing around with this fix. As a simple player I wouldn't know how to benefit from the first two option but fog adjust is interesting. I think he tried to have a better fog (by better I mean more complex fog like in SH2) by multiplying it's layers density. And it works. But there is a big catch: the thicker the fog gets the lesser you will see. First I've tried the fix's own values without touching anything. I couldn't see anything, in that kind of fog you will lose your sense of direction and get lost. I couldn't even see the road line I've been onto and I lost Heather herself completely in the fog when camera zoom out :) That's simply unplayable. Then I lower the values as much as I could -it seems he'd multiplied fog layers with 3, I tried with 2 and so on to get an acceptable rate; but when I did, it didn't look any different than the original fog. So I come to conclusion that the fog's problem is not it's density but it's quality. Otherwise the original fog is perfectly and cleverly calculated so you can have enough fog and you will be able to see what you need to see, nothing more, nothing less. The problem is it just looks pixelated and very square-ish on PC on high res monitors. I wonder if fog has it's own resolution like shadows and DOF?  That would be the real answer to fog problem.

I like how this fix renders the static elements in their correct aspect ratio instead of stretching the image. Things like title menu, inventory screen and FMV's are all 4:3. It was a nice feature to add to sh3proxy imo.

**Comment by Keith94** [comment]
Yeah, the author of the fix released some videos demonstrating what can be done with the fog + render distance, which is quite interesting (particularly the No Fog seems helpful in some ways):

[Silent Hill 3 No Fog Test](https://www.youtube.com/watch?v=PI7EsNJoAdw)
[Silent Hill 3 Custom Fog Test](https://www.youtube.com/watch?v=nxHi_jSolsw)
[Silent Hill 3 Custom Fog Test №2](https://www.youtube.com/watch?v=lEWW1Y9F8JI)

**Comment by CHNSK** [comment]
I wish this was for SH2. It is known that SH2 PC has way less fog than the original PS2 version. It could use that.

**Comment by ready2rumble** [comment]
Hey, Markeron, there is a ps2 version available on his website. 

http://ps2wide.net/pc.html#sh2

**Comment by CHNSK** [comment]
Yeah, I've seen that. He added it later. It's great.

**Comment by 07151129** [comment]
Note that the fog fix is also compatible with other SH2 patches (e.g. sh2proxy).
